### ISSUE TITLE
cartographer不能主动建图

### ISSUE THREAD

**Issue by numb0824** [mywisdomfly/Clean-robot-turtlebot3#2]
大佬您好，我从b站看到您的视频过来的，clone您的仓库之后也的确可以用。但是当我测试exlore lite with cartographer 的时候，就不行了。想问您一下，您测试过cartographer配合explore lite的使用吗？
我去explore lite的github里面看他的issue了，的确有这个问题，https://github.com/hrnr/m-explore/issues/28。
还有一个不情之请，，，您方便留一下某种方便的联系方式吗？比如邮箱或者微信？

**Comment by li-haojia** [comment]
您好，实在不好意思，我没测试过exlore lite with cartographer，不过我觉得只要可以和move_base 兼容即可（利用map_sever发布地图）。我的微信在B站上私信发您了。
