### ISSUE TITLE
全路径规划到达起点后没有下一目标点

### ISSUE THREAD

**Issue by miaoruonan** [mywisdomfly/Clean-robot-turtlebot3#3]
你好，我使用你的全覆盖路径代码，但是到达起点之后不能发布下一目标点是什么原因的。

**Comment by li-haojia** [comment]
能提供一个更详细的描述吗？

**Comment by qiyang1993** [comment]
> 能提供一个更详细的描述吗？
通过rosnode list,发现有/path_planning_node 和 /next_goal节点，rostopic echo /next_goal， topic does not appear to be published yet, 界面一直发送  count  : 0

**Comment by qiy2021** [comment]
> 能提供一个更详细的描述吗？

通过rosnode list,发现有/path_planning_node 和 /next_goal节点，rostopic echo /next_goal， topic does not appear to be published yet
界面信息：
count : 0
...
[path_planning_node-10] process has died [pid ...,...]

**Comment by li-haojia** [comment]
是没有规划路径？ 还是说没有执行？

**Comment by qiy2021** [comment]
> 是没有规划路径？ 还是说没有执行？

没有规划出路径，机器人原地不动，或者说走了几步就出错中断了，一直发count : 0。
错误信息：[path_planning_node-10] process has died [pid 29639, exit code -6, cmd /home/qiy/catkin_ws/devel/lib/clean_robot/path_planning_node __name:=path_planning_node __log:=/home/qiy/.ros/log/cb188506-5936-11eb-a273-00e04c3bbaee/path_planning_node-10.log].

经过查找原因：terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0) /home/qiy/下载/opencv-4.0.0/modules/imgproc/src/drawing.cpp:1811: error: (-215:Assertion failed) 0 < thickness && thickness <= MAX_THICKNESS in function 'line'
个人感觉是在opencv中出错了，还望大佬指点

**Comment by qiy2021** [comment]
> 是没有规划路径？ 还是说没有执行？

**Comment by qiy2021** [comment]
> > 是没有规划路径？ 还是说没有执行？

既没有规划路径，也没有执行

**Comment by li-haojia** [comment]
你用的ros版本是多少呀？我看你的opencv 是4.0的。我测试通过的环境的是ros melodic 和kinetic   opencv 3.2

**Comment by qiy2021** [comment]
> 你用的ros版本是多少呀？我看你的opencv 是4.0的。我测试通过的环境的是ros melodic 和kinetic opencv 3.2

ubuntu18.04 LTS + melodic , opencv4.0

**Comment by li-haojia** [comment]
你试试把`CleaningPathPlanner.cpp`的649行

```cpp
writeResult(resultMat, pathVec_); 
```
注释掉

**Comment by qiy2021** [comment]
> 你试试把`CleaningPathPlanner.cpp`的649行
> 
> ```c++
> writeResult(resultMat, pathVec_); 
> ```
> 
> 注释掉

问题解决了，能问下为什么？要是我怎么也想不到注释这句代码

**Comment by li-haojia** [comment]
这个函数里面调用了line（画线的）  opencv 4.0对他参数进行了一个检查，我之前写的没有符合这个检查（他是int型的 我用了小数 0.3 导致转换时候会变成0）。实际上这一个函数在ros中没什么用，只是用opencv 可视化的一个函数， 所以注释掉就好了。

**Comment by li-haojia** [comment]
> > 你试试把`CleaningPathPlanner.cpp`的649行
> > ```c++
> > writeResult(resultMat, pathVec_); 
> > ```
> > 
> > 
> > 注释掉
> 
> 问题解决了，能问下为什么？要是我怎么也想不到注释这句代码

（我写的代码不规范造成的 逃：）

**Comment by li-haojia** [comment]
代码已更新
