### ISSUE TITLE
next_goal發送目標點只有執行一次

### ISSUE THREAD

**Issue by kc944201** [mywisdomfly/Clean-robot-turtlebot3#4]
@mywisdomfly 
你好，目前正在參考你的貢獻，套用到自己機器人上
並且環境地圖是實際建置的，而非Gazebo模擬環境
目前遇到的問題是我執行後，next_goal發送目標點只有發送一次
可以請問可能的原因嗎?
謝謝你!
![image](https://user-images.githubusercontent.com/57080316/114162413-a852bb80-995b-11eb-91aa-8ee85ceac388.png)

**Comment by li-haojia** [comment]
你的机器人有动吗？是在第一个目标点附近转圈吗？

**Comment by kc944201** [comment]
@mywisdomfly 你好
開啟Rviz後，next_pose會發布一個目標點，機器人前往那個目標
但是機器人到達後，next_pose並沒有發布下個目標，不知道為什麼

**Comment by li-haojia** [comment]
您检查一下里程计的topic是否接入正确，使用 rosrun rqt_graph rqt_graph 看一下话题关系。

**Comment by kc944201** [comment]
收到謝謝回應，我再檢查看看!
