### ISSUE TITLE
启动之后机器人一直不动

### ISSUE THREAD

**Issue by ldepn** [mywisdomfly/Clean-robot-turtlebot3#6]
你好，我启动roslaunch clean_robot auto_slam.launch之后，机器人一直不动。

**Comment by ldepn** [comment]
跑的是melodic版本，提示警告 
Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.

**Comment by 911wb** [comment]
你好，可以用cartographer建图吗？

**Comment by liylin6688** [comment]
您的邮件已经收到，我将尽快回复！
                                                      ——李应林

**Comment by li-haojia** [comment]
> 你好，可以用cartographer建图吗？
应该可以，但是我没测试

**Comment by li-haojia** [comment]
> 跑的是melodic版本，提示警告 Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.

不好意，我还没遇到过这个问题

**Comment by pjs9115916** [comment]
Have you solved this bug?   if you are   please tell me     my emai: panjisong@cuhk.edu.cn.

**Comment by liylin6688** [comment]
您的邮件已经收到，我将尽快回复！
                                                      ——李应林

**Comment by Xin-mango** [comment]
你好，请问你的这个问题解决了吗，我的机器人是在跑我自己用cartographer生成的图后转了两圈就卡死了。
