### ISSUE TITLE
How is the cleared area painted?

### ISSUE THREAD

**Issue by kislyyhomyak** [mywisdomfly/Clean-robot-turtlebot3#7]
I need to make it so that, depending on the number of visits to a particular area of ​​the map, the color of the path traveled changes. in other words: if the robot passed 1 time, then it was painted over in red (as it is now), if twice, then blue, three times - yellow, etc.
can it be done? if so, how?

**Comment by li-haojia** [comment]
It is a message type named nav_msgs/Path in ROS. (http://docs.ros.org/en/lunar/api/nav_msgs/html/msg/Path.html)
You can plot different paths by yourself.

**Comment by liylin6688** [comment]
您的邮件已经收到，我将尽快回复！
                                                      ——李应林

**Comment by JackRen88** [comment]
Hello, @mywisdomfly 
Your work is great，can you provide the papers involved in the planning algorithm?

**Comment by li-haojia** [comment]
Sorry, the algorithm is very simple. The robot just traverses all the grid of the map. There is no paper.
