### ISSUE TITLE
error while running the cleaning simulation.

### ISSUE THREAD

**Issue by kislyyhomyak** [mywisdomfly/Clean-robot-turtlebot3#8]
the robot passes part of the room, then the program abruptly crashes and writes the following:
REQUIRED process [rviz-9] has died!
process has died [pid 15078, exit code -8, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/dmitriy/catkin_ws/src/Clean-robot-turtlebot3/clean_robot/rviz/turtlebot3_navigation.rviz __name:=rviz __log:=/home/dmitriy/.ros/log/e8810e3a-be37-11ec-b290-1c872c560276/rviz-9.log].
log file: /home/dmitriy/.ros/log/e8810e3a-be37-11ec-b290-1c872c560276/rviz-9*.log
Initiating shutdown!
what can cause this error?

**Comment by li-haojia** [comment]
I haven't met this problem. It just seems the visualization node has dead.
