### ISSUE TITLE
18.04 + opencv4.0，可以规划出全局路径，但是机器人只在原地旋转，然后停止。提示两个warning。

### ISSUE THREAD

**Issue by pjs9115916** [mywisdomfly/Clean-robot-turtlebot3#9]
`[ WARN] [1651200816.627344322]: The goal sent to the navfn planner is off the global costmap. Planning will always fail to this goal.
[ WARN] [1651200816.684746383]: Pose 'Goal' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
`
确认切换到了melodic分支，运行时还是出现了原地旋转的问题，看count 一直是0。大佬能帮忙分析分析吗

**Comment by li-haojia** [comment]
可能是地图问题或者opencv版本太新？
